{% set name = "nbjuniper" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbjuniper-{{ version }}.tar.gz
  sha256: d78f5184059be1292241541a4271ec75f73c86b16406de4b6b8b46d2afe7606e

build:
  number: 0
  noarch: python
  entry_points:
    - nbjuniper = nbjuniper.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - markdown >=3.2.2,<4.0.0
    - python >=3.6,<4.0
    - pyyaml >=5.3.1,<6.0.0

test:
  imports:
    - nbjuniper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashtonmv/nbjuniper
  summary: Convert IPython notebooks to executable HTML files with Juniper.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ashtonmv
